# 動態網頁爬蟲 - API Request

* 了解 API Request 用於動態網頁爬蟲的原理
* 能夠使用 API Request 撰寫動態網頁爬蟲

## 作業目標


* 根據範例使用 API 取出 高雄市小港區 2019 年 空氣品質 資料，並用一個適合的資料結構儲存
* Hint: 將所有資料存在一個變數當中

In [7]:
import requests
url = 'https://taqm.epa.gov.tw/taqm/tw/MonthlyAverage.aspx'
payload = {
    'ctl05$ddlSite': 58,
    'ctl05$ddlYear': 2019,
    'ctl05$btnQuery': '查詢',
    'ScriptManager1': 'ctl05$UpdatePanel1|ctl05$btnQuery',
    '__VIEWSTATE': 'q2AcLdVL4uFIWY8T6dvp4c4LEfMpHKqPY/EOVL3CUgYGmI0Gp+mtTESQIvTmq+CV2f70SVok0gxE/hG7vziJaOBNGjhYNJdDzR+4xJbubWtDIKquWHUbqtILS8sHslLMGgHiMhSaKfRhUkVf9f/YSFF9ZngPHRYtsRW03tAmJHVYpwwgqJ2rilBbtLoJcuJR4iXvtjZp0FVyJmz4Lw4G8umjfAtkHimXTLLvLxjBZcii/lCPpiWOuHePzStgtwBpkV0FGjBh+P5QWR8HxJu4SjuscTwjYrbB7TZ+RHwqU1+rH5dEryhFqoaRjv52TbowZvDq5yuqhYmEF6Ilj+fwjThoCPmWxUU0A17dLvVDL4G9u9TZhiNyU2x/Y1OBBY9Qn+nOzRd6mLhxEJ+neu6loSHojo6+qVokTJHgdF+oB+1BR+AeUOxELVWmQ/B6P7tdsnKQ4S4BBSlMgIKYze24JnNMvMti8dQ7FwJgwVSqn95z3MjeZE1b4RM3MrHEvT+Kg8o3NHLljLLCazs3A3p7ZD7rd21Bwp1d9ky3vDBd5wJZy2OM4npraNkpE6LvHPC+KiN5RsUjteja3aJc8J0i75mMROYECpO7t4jL3QRl5TO0sU3LVs0uj1anJwsiD6f1PAQT/hVvDZ3ecsjn7P/8eJv1d8CPf5vURVSMVPf8kF4wIctT0PFc05UkYDytikAObPvRh+jcyXU+dbNSDzAUTngc1AB3d2FwCxOrG2ZGBOQYpv7whJ9R9JMZOZrXhEiwabxOz48DhyMrzQpmFMKXuLCbROhunAPwu9XuFyy+bCo1/4qaKs5spXR6lA8pSfPDe66ZOu0gmVC/mKldvUJrXqZHL3NRDYaeBwb/MPIrLwoTzACW2RK86mYcUw4P5q2sn5M7zzwMPLsmnMNpS5KT8j0JnaNBe79sI4Dqpxn1aPFtzrsbP6WFKOP/GtT1zO+fjoJvhPK5VzapdxjonbvPstN1hHDiBDuMFN1vfRlyeN/lteS+qAnC1VOrHDirgB5wrKlzJT/VXe9OqCX/EUHvY3OJjdlfnHgk+o3RDlU4f7ArWUUA36nJ3RGP9zzSA0x31Zk5Fl4Mqjm7Z6qe2eILQGHHsZJf8XsA6CdG1/nnQM/PcIdez4xianpsvsLLrmKGbSCM1idCltd9hD3XM3V0btP/IUVkbzxMWKUmL2KVP9E0+OsNCz06CD6Goea3nf69ymo6Ne+xWZv8OJPA/wogwvVRumbeGVYGXH4w/ZvAU8bNNGXQ6V2KWu3jNCEY7ZGy6fvqRjyWY+VegMbxjP49Xs2BIydL9bYMgxE7NIACriup1VqQZtaK2/RW9sPcQ3w9ewlg4VO+J43WbzpqjUqVbMdy41Jn78v7jxluLhz45ZWWh4S2MXqof/G/U55YubnkP85lWcgSICB1NhlYL/UI8GiVfSkJZpJ08Etj0Qoldlh3uLoTWS5YjsWqVCqh0iWBi9Bwad3bKEbMgewlenYfooW/C7kxGGusXfk8qTY0MRJaWH6r3DMdQZM25zAlMinNmDkZjKA50vFfMlVzcFOXPEg8z0t5O8Y4iIBvF3td62P9ktwHw9ZAgqayuR5zfGFNOdIYbunWUV3syXz4cT0ty+UO84oNLLhLOF67tOtMXDipZvB8CND6xdpNN18/gDs4A8KvGzEdhirE0iT/o/YcJhXwpJKOYDmgmTBfivCfvBU2HsPgwIBwt6A7IUsbxEa5KW9WjhpGyktHYFkRxDYK9o4X+tMUQd63c/K4LC+ss2pEk8XL3g1myQBqAYjh1flH57IgMjZL5arB8XMbuaP/68UPyQjkekCKnRxqtOH7NnhIwvk2dO1wjYlI+7oWx05SdZl8MFxD9845SUpFhvqUIs+Ed1kyXYw/VEHcMHTJ+V/x2hGzGEVknGS//5uL3W7ecH4ekZn4nI1Mdswy5MqbZaiTWmbiw5RGOZcvOD9RzxU8TsOl70ZK7e3+9x6I3AmPPGJ32uWxrzKAaBgUMxbxS7ZVpSyLetOrTmsjAFcfJ++GQ5BxXJJ1xbkmlYYl/tGt5cE2kQ+vLQ8i6sV94TjYI+2GfMSJB72zJlLWANcuaQMWwdwsQkH3xGqwC4YTPvViLPCGywbWgZtgRHSQ26lSGGR34YlxR6Pg2lXKb0DoG5cqdwLWiT9w4/DuIbdLQOLxYB/tfeZiL4Kjk4nucAtpkaDVpqqOfjgVmiGbqOq6km6uVOeDaVqyGJZK24mE4MOV4H77zORUle/krZ04ZuuPJqqMwlxB5EKK5JGoPj+pVE3xBx//8bFjQt5KCZeldCeVi3aRHT9p3H2X+pP7e1GTwtzPIMF7/HL3ic2Fk2RbCuksYNWN8ilhfWanRVlfrJDrOd9i+XLBdeIf0+yeGasAKAEys16F4bK/1nxEtCOlYliIBGtcklQn1CYiZ+6wFUzDw6nDOfWd/HPDWctoU4F9GtmZa0jA7vqBxBnYbwx+RiANxdlQEncs5Kk7fWfCJn8+6wDUbcieVjpMI7nuEgcnQI2y+50f6B62yPHeRoD99N/kI4c2qjBWzbJIMkLYsFPsAV5HvRhEk525HjQuKIA0w6361elZja271xNGxasrOWcnLwY1n7bGdTmrXYXKGO39TkRJXslvLDwhEycGkQGTNB/hndqsrVhm568DfYG6fELAKj6rIZvM4oBr54K6+d5wsI5ay1eKiYzjR1Z1rZTAWCwqKI+fKLz9k8XGNx3MaBzuTH54AG2WIBzFqsO/Cc2RSuCWdpgzF3Yc0OF73FPHP9H45FRbMZwQGURNgySjg6BMKZILaTxFa7d5wJxuIZP47axQe5Tvh+A8YkTfaYGjmEmmUQEsVZuVwN7OeO6Wt+w67BTyY8ZIbMzrT40rdGoVlVSHLgWtukSVAEJVNHgouUWA0Q/vbiCRagB3hIAY8qZJVUV5q7R+zT1MWFdDA/zwOP6fBBVdmYWQplxelkbz+JC0n1y+JQ4c7nI6VCyo+GZ1egi6Tv0eba7/Iw8J+06sZUpsD1VvfQgyAsAHhd0kJW/jBPO5P1fwbfugmD2HpqR39XvIezEqvTSiNP8IAAOmXc8WOlWyQ5tiTAXyA4V53oFy56GYJntu9zLO07xFxvLtMocU',
    '__EVENTVALIDATION': 'L1x+9+dMp5Cz8WBmLza/VLfSccBXAmeOpCyCGXp2Tv6kTFnbolWYSg/ZogPd3U/GQkcWqM6AUugJg3VYyjSA8OjxNf6I1RpbEfkoOfKUFFDSvZwciOjnaK1sEdWLxHXygfrfk0AjsUbNnHvpz71Mj3BaFmpF8eD/bhRjdKNlQK20iXrDH6P6fSmjpOunyGvvtg5SzP1BagcFjt2wkzNJLzoQPIObDUPFOnPZjMMzVXtM2N42pCFM/UVKM6Av/noqHHSQARHIjrGWH7LHz3iJeZi/4W0Y12SiOhbkAvQyfvkoGpMG7XOr5vS8vCnUkoVGQ9eE6t7u85hcnqCRd/RuKTIIAJPcLQ+UlXAAjIGKeGYXmvoPL8V+ZZuUYGkEwiKV9hFzz6UuhsUktE4RUjdsN2XTf107J/TEdT49nkHJggKeGJBYYYmV46gq6SHAipVwxBifvNFtcZ2pr/z+EtMJxcM895hCNOHfd0vJR9s5WwKe1JjnuyRYu6oKvjN0zOsddhGXddgj6+SZ/Xlg8k8XvE7IISfw9ejaUNNn9sPGu+7IcQiD5u7cBCZKpDxgtl2LEQCpO1e9BHiKM9r/DlLue0Hem2YEDQijPpCuewZMA0854dJMJn8u9hXG1aBkkLPqjpgxcLK8hBSOVLMjTA6hXq6EAneKlKHXy0efiu43V+fWLcCr7mA4udcW+ekvB89HTxzo10SBnS21GSVsdC7kkS8tocFnokC0vJQAlLdWh9pCKnNCNNOMSmSFQ+xHoF475oK27g8ZBgQwvQ+BPm+8rQzmkOgMVPVYV6FCDHFm/cfpmvoCe4MYAZy91uXqUKNmpngdHp0JW/ip6DP49y1K3phiFp6pSzwwKI3LXJWEFAXy5ihM1j8l1WMq+Z2ZzKYAwcD6WlqM6htc9GYzUZ0Gt85CA9vsmE/ELP1fOH2yUipQUzzlT5o6MoL8RHOMLNnN2X0TU36U+oxJm9GXhtqrPRPZHxM=',
    '__VIEWSTATEGENERATOR': '0C858E1A'
}
r = requests.post(url, data=payload)
r.status_code

200

![](https://imgur.com/obLkbFe.jpg)

In [8]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(r.text, 'html.parser')
table = soup.find('table', class_='TABLE_G')
print(table)

<table align="Center" border="1" cellpadding="3" cellspacing="0" class="TABLE_G" id="ctl05_gv" rules="all" style="border-color:Black;border-width:1px;border-style:None;border-collapse:collapse;">
<tr style="color:Black;font-weight:normal;">
<th scope="col">監測項目</th><th scope="col">單位</th><th scope="col">監測日期</th><th scope="col">監測值</th><th scope="col">標註</th>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">SO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2019/01</td><td>4.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>3.30</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>3.90</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>3.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>3.30</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>4.10</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>4</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>4.60</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>3.50</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>3.20</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>3.60</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>3</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">CO</td><td class="no-alt" rowspan="12" valign="top">ppm</td><td>2019/01</td><td>0.67</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>0.48</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>0.50</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>0.39</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>0.38</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>0.24</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>0.28</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>0.33</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>0.32</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>0.36</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>0.46</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>0.54</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">O3</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2019/01</td><td>24.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>29.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>29.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>30.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>28.60</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>16.30</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>15.50</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>19.70</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>35.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>44</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>34.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>22.30</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">PM10</td><td class="no-alt" rowspan="12" valign="top">μg/m3</td><td>2019/01</td><td>78</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>57</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>52</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>42</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>35</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>20</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>24</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>27</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>35</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>50</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>63</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>54</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NOx</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2019/01</td><td>38.01</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>25.62</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>27.84</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>21.83</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>22.55</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>17.15</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>17.71</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>19.66</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>18.66</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>19.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>28.99</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>33.84</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2019/01</td><td>7.95</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>4.76</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>5.41</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>4.16</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>4.58</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>5.08</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>5.16</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>5.17</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>3.63</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>3.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>5.21</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>7.83</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2019/01</td><td>30.06</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>20.86</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>22.43</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>17.68</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>17.98</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>12.08</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>12.54</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>14.49</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>15.03</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>15.99</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>23.78</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>26</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">THC</td><td class="no-alt" rowspan="12" valign="top">ppm</td><td>2019/01</td><td>2.27</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>2.11</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>2.12</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>2.02</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>2.02</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>1.92</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>1.93</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>1.97</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>1.98</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>2.05</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>2.15</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>2.18</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NMHC</td><td class="no-alt" rowspan="12" valign="top">ppm</td><td>2019/01</td><td>0.27</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>0.17</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>0.18</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>0.14</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>0.16</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>0.13</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>0.14</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>0.15</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>0.13</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>0.13</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>0.21</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>0.23</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">CH4</td><td class="no-alt" rowspan="12" valign="top">ppm</td><td>2019/01</td><td>2</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>1.94</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>1.94</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>1.88</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>1.86</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>1.79</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>1.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>1.82</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>1.86</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>1.92</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>1.94</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>1.95</td><td> </td>
</tr>
</table>

In [11]:
import re
data = {}
subdata = {}
month = 1
a = table.find_all(name='tr')
for b in a: 
    c = b.find_all(name='td')
    if not c == []:
        if len(c) > 3:
            if month == 13:
                subdata = {}
                month = 1
            dataTitle = c[0].string
            subdata[c[2].string] = c[3].string
            month +=1
        else:
            subdata[c[0].string] = c[1].string
            if month == 12:
                data[dataTitle] = subdata
            month +=1
            
data

{'SO2': {'2019/01': '4.10',
  '2019/02': '3.30',
  '2019/03': '3.90',
  '2019/04': '3.40',
  '2019/05': '3.30',
  '2019/06': '4.10',
  '2019/07': '4',
  '2019/08': '4.60',
  '2019/09': '3.50',
  '2019/10': '3.20',
  '2019/11': '3.60',
  '2019/12': '3'},
 'CO': {'2019/01': '0.67',
  '2019/02': '0.48',
  '2019/03': '0.50',
  '2019/04': '0.39',
  '2019/05': '0.38',
  '2019/06': '0.24',
  '2019/07': '0.28',
  '2019/08': '0.33',
  '2019/09': '0.32',
  '2019/10': '0.36',
  '2019/11': '0.46',
  '2019/12': '0.54'},
 'O3': {'2019/01': '24.70',
  '2019/02': '29.40',
  '2019/03': '29.20',
  '2019/04': '30.40',
  '2019/05': '28.60',
  '2019/06': '16.30',
  '2019/07': '15.50',
  '2019/08': '19.70',
  '2019/09': '35.70',
  '2019/10': '44',
  '2019/11': '34.80',
  '2019/12': '22.30'},
 'PM10': {'2019/01': '78',
  '2019/02': '57',
  '2019/03': '52',
  '2019/04': '42',
  '2019/05': '35',
  '2019/06': '20',
  '2019/07': '24',
  '2019/08': '27',
  '2019/09': '35',
  '2019/10': '50',
  '2019/11': '63',
  '2019/12': '54'},
 'NOx': {'2019/01': '38.01',
  '2019/02': '25.62',
  '2019/03': '27.84',
  '2019/04': '21.83',
  '2019/05': '22.55',
  '2019/06': '17.15',
  '2019/07': '17.71',
  '2019/08': '19.66',
  '2019/09': '18.66',
  '2019/10': '19.50',
  '2019/11': '28.99',
  '2019/12': '33.84'},
 'NO': {'2019/01': '7.95',
  '2019/02': '4.76',
  '2019/03': '5.41',
  '2019/04': '4.16',
  '2019/05': '4.58',
  '2019/06': '5.08',
  '2019/07': '5.16',
  '2019/08': '5.17',
  '2019/09': '3.63',
  '2019/10': '3.50',
  '2019/11': '5.21',
  '2019/12': '7.83'},
 'NO2': {'2019/01': '30.06',
  '2019/02': '20.86',
  '2019/03': '22.43',
  '2019/04': '17.68',
  '2019/05': '17.98',
  '2019/06': '12.08',
  '2019/07': '12.54',
  '2019/08': '14.49',
  '2019/09': '15.03',
  '2019/10': '15.99',
  '2019/11': '23.78',
  '2019/12': '26'},
 'THC': {'2019/01': '2.27',
  '2019/02': '2.11',
  '2019/03': '2.12',
  '2019/04': '2.02',
  '2019/05': '2.02',
  '2019/06': '1.92',
  '2019/07': '1.93',
  '2019/08': '1.97',
  '2019/09': '1.98',
  '2019/10': '2.05',
  '2019/11': '2.15',
  '2019/12': '2.18'},
 'NMHC': {'2019/01': '0.27',
  '2019/02': '0.17',
  '2019/03': '0.18',
  '2019/04': '0.14',
  '2019/05': '0.16',
  '2019/06': '0.13',
  '2019/07': '0.14',
  '2019/08': '0.15',
  '2019/09': '0.13',
  '2019/10': '0.13',
  '2019/11': '0.21',
  '2019/12': '0.23'},
 'CH4': {'2019/01': '2',
  '2019/02': '1.94',
  '2019/03': '1.94',
  '2019/04': '1.88',
  '2019/05': '1.86',
  '2019/06': '1.79',
  '2019/07': '1.80',
  '2019/08': '1.82',
  '2019/09': '1.86',
  '2019/10': '1.92',
  '2019/11': '1.94',
  '2019/12': '1.95'}}

In [12]:
import pandas as pd
pd.DataFrame(data)

          SO2    CO     O3 PM10    NOx    NO    NO2   THC  NMHC   CH4
2019/01  4.10  0.67  24.70   78  38.01  7.95  30.06  2.27  0.27     2
2019/02  3.30  0.48  29.40   57  25.62  4.76  20.86  2.11  0.17  1.94
2019/03  3.90  0.50  29.20   52  27.84  5.41  22.43  2.12  0.18  1.94
2019/04  3.40  0.39  30.40   42  21.83  4.16  17.68  2.02  0.14  1.88
2019/05  3.30  0.38  28.60   35  22.55  4.58  17.98  2.02  0.16  1.86
2019/06  4.10  0.24  16.30   20  17.15  5.08  12.08  1.92  0.13  1.79
2019/07     4  0.28  15.50   24  17.71  5.16  12.54  1.93  0.14  1.80
2019/08  4.60  0.33  19.70   27  19.66  5.17  14.49  1.97  0.15  1.82
2019/09  3.50  0.32  35.70   35  18.66  3.63  15.03  1.98  0.13  1.86
2019/10  3.20  0.36     44   50  19.50  3.50  15.99  2.05  0.13  1.92
2019/11  3.60  0.46  34.80   63  28.99  5.21  23.78  2.15  0.21  1.94
2019/12     3  0.54  22.30   54  33.84  7.83     26  2.18  0.23  1.95

In [9]:
import re
data = {}
subdata = {}
month = 1
a = table.find_all(name='tr')
for b in a: 
    c = b.find_all(name='td')
    if not c == []:
        if len(c) > 3:
            if month == 13:
                subdata = {}
                month = 1
            dataTitle = c[0].string
            subdata[c[2].string] = c[3].string
            month +=1
        else:
            subdata[c[0].string] = c[1].string
            if month == 12:
                data[dataTitle] = subdata
            month +=1
            
data

{'SO2': {'2019/01': '4.10',
  '2019/02': '3.30',
  '2019/03': '3.90',
  '2019/04': '3.40',
  '2019/05': '3.30',
  '2019/06': '4.10',
  '2019/07': '4',
  '2019/08': '4.60',
  '2019/09': '3.50',
  '2019/10': '3.20',
  '2019/11': '3.60',
  '2019/12': '3'},
 'CO': {'2019/01': '0.67',
  '2019/02': '0.48',
  '2019/03': '0.50',
  '2019/04': '0.39',
  '2019/05': '0.38',
  '2019/06': '0.24',
  '2019/07': '0.28',
  '2019/08': '0.33',
  '2019/09': '0.32',
  '2019/10': '0.36',
  '2019/11': '0.46',
  '2019/12': '0.54'},
 'O3': {'2019/01': '24.70',
  '2019/02': '29.40',
  '2019/03': '29.20',
  '2019/04': '30.40',
  '2019/05': '28.60',
  '2019/06': '16.30',
  '2019/07': '15.50',
  '2019/08': '19.70',
  '2019/09': '35.70',
  '2019/10': '44',
  '2019/11': '34.80',
  '2019/12': '22.30'},
 'PM10': {'2019/01': '78',
  '2019/02': '57',
  '2019/03': '52',
  '2019/04': '42',
  '2019/05': '35',
  '2019/06': '20',
  '2019/07': '24',
  '2019/08': '27',
  '2019/09': '35',
  '2019/10': '50',
  '2019/11': '63',
  '2019/12': '54'},
 'NOx': {'2019/01': '38.01',
  '2019/02': '25.62',
  '2019/03': '27.84',
  '2019/04': '21.83',
  '2019/05': '22.55',
  '2019/06': '17.15',
  '2019/07': '17.71',
  '2019/08': '19.66',
  '2019/09': '18.66',
  '2019/10': '19.50',
  '2019/11': '28.99',
  '2019/12': '33.84'},
 'NO': {'2019/01': '7.95',
  '2019/02': '4.76',
  '2019/03': '5.41',
  '2019/04': '4.16',
  '2019/05': '4.58',
  '2019/06': '5.08',
  '2019/07': '5.16',
  '2019/08': '5.17',
  '2019/09': '3.63',
  '2019/10': '3.50',
  '2019/11': '5.21',
  '2019/12': '7.83'},
 'NO2': {'2019/01': '30.06',
  '2019/02': '20.86',
  '2019/03': '22.43',
  '2019/04': '17.68',
  '2019/05': '17.98',
  '2019/06': '12.08',
  '2019/07': '12.54',
  '2019/08': '14.49',
  '2019/09': '15.03',
  '2019/10': '15.99',
  '2019/11': '23.78',
  '2019/12': '26'},
 'THC': {'2019/01': '2.27',
  '2019/02': '2.11',
  '2019/03': '2.12',
  '2019/04': '2.02',
  '2019/05': '2.02',
  '2019/06': '1.92',
  '2019/07': '1.93',
  '2019/08': '1.97',
  '2019/09': '1.98',
  '2019/10': '2.05',
  '2019/11': '2.15',
  '2019/12': '2.18'},
 'NMHC': {'2019/01': '0.27',
  '2019/02': '0.17',
  '2019/03': '0.18',
  '2019/04': '0.14',
  '2019/05': '0.16',
  '2019/06': '0.13',
  '2019/07': '0.14',
  '2019/08': '0.15',
  '2019/09': '0.13',
  '2019/10': '0.13',
  '2019/11': '0.21',
  '2019/12': '0.23'},
 'CH4': {'2019/01': '2',
  '2019/02': '1.94',
  '2019/03': '1.94',
  '2019/04': '1.88',
  '2019/05': '1.86',
  '2019/06': '1.79',
  '2019/07': '1.80',
  '2019/08': '1.82',
  '2019/09': '1.86',
  '2019/10': '1.92',
  '2019/11': '1.94',
  '2019/12': '1.95'}}

In [13]:
import pandas as pd
pd.DataFrame(data)

          SO2    CO     O3 PM10    NOx    NO    NO2   THC  NMHC   CH4
2019/01  4.10  0.67  24.70   78  38.01  7.95  30.06  2.27  0.27     2
2019/02  3.30  0.48  29.40   57  25.62  4.76  20.86  2.11  0.17  1.94
2019/03  3.90  0.50  29.20   52  27.84  5.41  22.43  2.12  0.18  1.94
2019/04  3.40  0.39  30.40   42  21.83  4.16  17.68  2.02  0.14  1.88
2019/05  3.30  0.38  28.60   35  22.55  4.58  17.98  2.02  0.16  1.86
2019/06  4.10  0.24  16.30   20  17.15  5.08  12.08  1.92  0.13  1.79
2019/07     4  0.28  15.50   24  17.71  5.16  12.54  1.93  0.14  1.80
2019/08  4.60  0.33  19.70   27  19.66  5.17  14.49  1.97  0.15  1.82
2019/09  3.50  0.32  35.70   35  18.66  3.63  15.03  1.98  0.13  1.86
2019/10  3.20  0.36     44   50  19.50  3.50  15.99  2.05  0.13  1.92
2019/11  3.60  0.46  34.80   63  28.99  5.21  23.78  2.15  0.21  1.94
2019/12     3  0.54  22.30   54  33.84  7.83     26  2.18  0.23  1.95